import type { WorkflowGraph } from "@codebrix/types";

export interface PipelineTemplate {
  id: string;
  title: string;
  category: "classification" | "regression" | "clustering" | "preprocessing";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  description: string;
  tags: string[];
  nodeCount: number;
  edgeCount: number;
  graph: WorkflowGraph;
}

export const PIPELINE_TEMPLATES: PipelineTemplate[] = [
  {
    id: "template-kaggle-titanic",
    title: "Titanic Survival Classification",
    category: "classification",
    difficulty: "Beginner",
    description: "Production ML benchmark: imputes missing passenger ages, one-hot encodes categorical demographics, scales fares, trains an ensemble Random Forest, and outputs accuracy scoring & confusion matrix.",
    tags: ["Titanic", "Classification", "Random Forest", "Imputation", "One-Hot"],
    nodeCount: 9,
    edgeCount: 11,
    graph: {
      id: "wf-kaggle-titanic",
      name: "Titanic Survival Classifier",
      version: "1.0.0",
      description: "Titanic survival baseline with Random Forest and preprocessing",
      blocks: {
        "blk-csv": {
          id: "blk-csv",
          definitionId: "data.csv_loader",
          label: "Titanic Dataset (train.csv)",
          position: { x: 40, y: 160 },
          config: { filePath: "data/titanic.csv" },
          state: "idle",
        },
        "blk-impute": {
          id: "blk-impute",
          definitionId: "prep.imputer",
          label: "Missing Age/Fare Imputer",
          position: { x: 280, y: 160 },
          config: { strategy: "median" },
          state: "idle",
        },
        "blk-encode": {
          id: "blk-encode",
          definitionId: "prep.encoder",
          label: "Categorical One-Hot Encoder",
          position: { x: 520, y: 160 },
          config: { method: "onehot" },
          state: "idle",
        },
        "blk-scale": {
          id: "blk-scale",
          definitionId: "prep.standard_scaler",
          label: "Continuous Feature Scaler",
          position: { x: 760, y: 160 },
          config: { with_mean: true, with_std: true },
          state: "idle",
        },
        "blk-split": {
          id: "blk-split",
          definitionId: "ml.train_test_split",
          label: "Train/Test Split (80/20)",
          position: { x: 1000, y: 160 },
          config: { test_size: 0.2, random_state: 42, target_column: "survived" },
          state: "idle",
        },
        "blk-rf": {
          id: "blk-rf",
          definitionId: "ml.random_forest_classifier",
          label: "Random Forest Classifier",
          position: { x: 1250, y: 90 },
          config: { n_estimators: 100, max_depth: 6, random_state: 42 },
          state: "idle",
        },
        "blk-pred": {
          id: "blk-pred",
          definitionId: "ml.predict",
          label: "Survival Predictor",
          position: { x: 1500, y: 160 },
          config: {},
          state: "idle",
        },
        "blk-acc": {
          id: "blk-acc",
          definitionId: "eval.accuracy",
          label: "Accuracy Score",
          position: { x: 1750, y: 100 },
          config: {},
          state: "idle",
        },
        "blk-cm": {
          id: "blk-cm",
          definitionId: "eval.confusion_matrix",
          label: "Confusion Matrix Heatmap",
          position: { x: 1750, y: 240 },
          config: {},
          state: "idle",
        },
      },
      connections: [
        { id: "c1", sourceBlockId: "blk-csv", sourcePortId: "dataset_out", targetBlockId: "blk-impute", targetPortId: "dataset_in" },
        { id: "c2", sourceBlockId: "blk-impute", sourcePortId: "dataset_out", targetBlockId: "blk-encode", targetPortId: "dataset_in" },
        { id: "c3", sourceBlockId: "blk-encode", sourcePortId: "dataset_out", targetBlockId: "blk-scale", targetPortId: "dataset_in" },
        { id: "c4", sourceBlockId: "blk-scale", sourcePortId: "dataset_out", targetBlockId: "blk-split", targetPortId: "dataset_in" },
        { id: "c5", sourceBlockId: "blk-split", sourcePortId: "train_data_out", targetBlockId: "blk-rf", targetPortId: "train_data_in" },
        { id: "c6", sourceBlockId: "blk-rf", sourcePortId: "model_out", targetBlockId: "blk-pred", targetPortId: "model_in" },
        { id: "c7", sourceBlockId: "blk-split", sourcePortId: "test_data_out", targetBlockId: "blk-pred", targetPortId: "test_data_in" },
        { id: "c8", sourceBlockId: "blk-pred", sourcePortId: "predictions_out", targetBlockId: "blk-acc", targetPortId: "predictions_in" },
        { id: "c9", sourceBlockId: "blk-split", sourcePortId: "y_test_out", targetBlockId: "blk-acc", targetPortId: "ground_truth_in" },
        { id: "c10", sourceBlockId: "blk-pred", sourcePortId: "predictions_out", targetBlockId: "blk-cm", targetPortId: "predictions_in" },
        { id: "c11", sourceBlockId: "blk-split", sourcePortId: "y_test_out", targetBlockId: "blk-cm", targetPortId: "ground_truth_in" },
      ],
    },
  },
  {
    id: "template-kaggle-house-prices",
    title: "House Prices Advanced Regression",
    category: "regression",
    difficulty: "Intermediate",
    description: "Housing valuation pipeline: drops non-predictive Id identifiers, imputes missing records, standardizes living areas, fits a Gradient Boosting Regressor, and computes RMSE, MAE, and R².",
    tags: ["House Prices", "Regression", "Gradient Boosting", "StandardScaler", "RMSE"],
    nodeCount: 8,
    edgeCount: 9,
    graph: {
      id: "wf-kaggle-house-prices",
      name: "House Prices Valuation Pipeline",
      version: "1.0.0",
      description: "House Prices regression pipeline with Gradient Boosting Regressor",
      blocks: {
        "blk-csv": {
          id: "blk-csv",
          definitionId: "data.csv_loader",
          label: "House Prices (train.csv)",
          position: { x: 40, y: 160 },
          config: { filePath: "data/house_prices.csv" },
          state: "idle",
        },
        "blk-drop": {
          id: "blk-drop",
          definitionId: "prep.drop_columns",
          label: "Drop Non-Predictive Id",
          position: { x: 280, y: 160 },
          config: { columns_to_drop: "Id" },
          state: "idle",
        },
        "blk-impute": {
          id: "blk-impute",
          definitionId: "prep.imputer",
          label: "Median Feature Imputer",
          position: { x: 520, y: 160 },
          config: { strategy: "median" },
          state: "idle",
        },
        "blk-scale": {
          id: "blk-scale",
          definitionId: "prep.standard_scaler",
          label: "Z-Score Standardization",
          position: { x: 760, y: 160 },
          config: { with_mean: true, with_std: true },
          state: "idle",
        },
        "blk-split": {
          id: "blk-split",
          definitionId: "ml.train_test_split",
          label: "Train/Test Split (80/20)",
          position: { x: 1000, y: 160 },
          config: { test_size: 0.2, random_state: 42, target_column: "SalePrice" },
          state: "idle",
        },
        "blk-gbr": {
          id: "blk-gbr",
          definitionId: "ml.gradient_boosting_regressor",
          label: "Gradient Boosting Regressor",
          position: { x: 1250, y: 100 },
          config: { n_estimators: 150, learning_rate: 0.08, max_depth: 3 },
          state: "idle",
        },
        "blk-pred": {
          id: "blk-pred",
          definitionId: "ml.predict",
          label: "Price Predictor",
          position: { x: 1500, y: 160 },
          config: {},
          state: "idle",
        },
        "blk-eval": {
          id: "blk-eval",
          definitionId: "eval.regression_metrics",
          label: "Evaluation Metrics (RMSE / R²)",
          position: { x: 1750, y: 160 },
          config: {},
          state: "idle",
        },
      },
      connections: [
        { id: "c1", sourceBlockId: "blk-csv", sourcePortId: "dataset_out", targetBlockId: "blk-drop", targetPortId: "dataset_in" },
        { id: "c2", sourceBlockId: "blk-drop", sourcePortId: "dataset_out", targetBlockId: "blk-impute", targetPortId: "dataset_in" },
        { id: "c3", sourceBlockId: "blk-impute", sourcePortId: "dataset_out", targetBlockId: "blk-scale", targetPortId: "dataset_in" },
        { id: "c4", sourceBlockId: "blk-scale", sourcePortId: "dataset_out", targetBlockId: "blk-split", targetPortId: "dataset_in" },
        { id: "c5", sourceBlockId: "blk-split", sourcePortId: "train_data_out", targetBlockId: "blk-gbr", targetPortId: "train_data_in" },
        { id: "c6", sourceBlockId: "blk-gbr", sourcePortId: "model_out", targetBlockId: "blk-pred", targetPortId: "model_in" },
        { id: "c7", sourceBlockId: "blk-split", sourcePortId: "test_data_out", targetBlockId: "blk-pred", targetPortId: "test_data_in" },
        { id: "c8", sourceBlockId: "blk-pred", sourcePortId: "predictions_out", targetBlockId: "blk-eval", targetPortId: "predictions_in" },
        { id: "c9", sourceBlockId: "blk-split", sourcePortId: "y_test_out", targetBlockId: "blk-eval", targetPortId: "ground_truth_in" },
      ],
    },
  },
  {
    id: "template-kaggle-customer-churn",
    title: "Telco Customer Churn Prediction",
    category: "classification",
    difficulty: "Intermediate",
    description: "Telecom customer retention pipeline: handles missing records, encodes categorical contract types with OneHot, normalizes charges, fits a regularized Logistic Regression classifier, and evaluates with F1 macro classification report.",
    tags: ["Customer Churn", "Logistic Regression", "F1 Score", "Classification Report"],
    nodeCount: 8,
    edgeCount: 9,
    graph: {
      id: "wf-kaggle-churn",
      name: "Telco Churn Prediction Pipeline",
      version: "1.0.0",
      description: "Customer churn prediction using Logistic Regression and One-Hot Encoding",
      blocks: {
        "blk-csv": {
          id: "blk-csv",
          definitionId: "data.csv_loader",
          label: "Telco Churn Dataset",
          position: { x: 40, y: 160 },
          config: { filePath: "data/customer_churn.csv" },
          state: "idle",
        },
        "blk-impute": {
          id: "blk-impute",
          definitionId: "prep.imputer",
          label: "Missing Charges Imputer",
          position: { x: 280, y: 160 },
          config: { strategy: "median" },
          state: "idle",
        },
        "blk-encode": {
          id: "blk-encode",
          definitionId: "prep.encoder",
          label: "Contract One-Hot Encoder",
          position: { x: 520, y: 160 },
          config: { method: "onehot" },
          state: "idle",
        },
        "blk-scale": {
          id: "blk-scale",
          definitionId: "prep.standard_scaler",
          label: "Monthly Charges Scaler",
          position: { x: 760, y: 160 },
          config: { with_mean: true, with_std: true },
          state: "idle",
        },
        "blk-split": {
          id: "blk-split",
          definitionId: "ml.train_test_split",
          label: "Train/Test Split (75/25)",
          position: { x: 1000, y: 160 },
          config: { test_size: 0.25, random_state: 42, target_column: "Churn" },
          state: "idle",
        },
        "blk-logreg": {
          id: "blk-logreg",
          definitionId: "ml.logistic_regression",
          label: "Logistic Regression (L2)",
          position: { x: 1250, y: 100 },
          config: { c_param: 1.0, max_iter: 200 },
          state: "idle",
        },
        "blk-pred": {
          id: "blk-pred",
          definitionId: "ml.predict",
          label: "Churn Predictor",
          position: { x: 1500, y: 160 },
          config: {},
          state: "idle",
        },
        "blk-report": {
          id: "blk-report",
          definitionId: "eval.classification_report",
          label: "Classification Report (F1 Macro)",
          position: { x: 1750, y: 160 },
          config: {},
          state: "idle",
        },
      },
      connections: [
        { id: "c1", sourceBlockId: "blk-csv", sourcePortId: "dataset_out", targetBlockId: "blk-impute", targetPortId: "dataset_in" },
        { id: "c2", sourceBlockId: "blk-impute", sourcePortId: "dataset_out", targetBlockId: "blk-encode", targetPortId: "dataset_in" },
        { id: "c3", sourceBlockId: "blk-encode", sourcePortId: "dataset_out", targetBlockId: "blk-scale", targetPortId: "dataset_in" },
        { id: "c4", sourceBlockId: "blk-scale", sourcePortId: "dataset_out", targetBlockId: "blk-split", targetPortId: "dataset_in" },
        { id: "c5", sourceBlockId: "blk-split", sourcePortId: "train_data_out", targetBlockId: "blk-logreg", targetPortId: "train_data_in" },
        { id: "c6", sourceBlockId: "blk-logreg", sourcePortId: "model_out", targetBlockId: "blk-pred", targetPortId: "model_in" },
        { id: "c7", sourceBlockId: "blk-split", sourcePortId: "test_data_out", targetBlockId: "blk-pred", targetPortId: "test_data_in" },
        { id: "c8", sourceBlockId: "blk-pred", sourcePortId: "predictions_out", targetBlockId: "blk-report", targetPortId: "predictions_in" },
        { id: "c9", sourceBlockId: "blk-split", sourcePortId: "y_test_out", targetBlockId: "blk-report", targetPortId: "ground_truth_in" },
      ],
    },
  },
  {
    id: "template-kaggle-fraud-detection",
    title: "Credit Card Fraud Anomaly Detection",
    category: "classification",
    difficulty: "Advanced",
    description: "High-stakes imbalanced anomaly detection: isolates extreme transaction outliers using IQR bounds, standardizes features with RobustScaler, trains an ensemble Random Forest, and outputs precision, recall, and macro F1.",
    tags: ["Fraud Detection", "Outlier Filter", "Random Forest", "Imbalanced Data"],
    nodeCount: 7,
    edgeCount: 8,
    graph: {
      id: "wf-kaggle-fraud",
      name: "Credit Card Fraud Detection",
      version: "1.0.0",
      description: "Imbalanced fraud detection pipeline with RobustScaler and Random Forest",
      blocks: {
        "blk-csv": {
          id: "blk-csv",
          definitionId: "data.csv_loader",
          label: "Transaction Dataset",
          position: { x: 40, y: 160 },
          config: { filePath: "data/creditcard.csv" },
          state: "idle",
        },
        "blk-outlier": {
          id: "blk-outlier",
          definitionId: "prep.outlier_filter",
          label: "IQR Outlier Filter",
          position: { x: 280, y: 160 },
          config: { iqr_multiplier: 2.0 },
          state: "idle",
        },
        "blk-scale": {
          id: "blk-scale",
          definitionId: "prep.robust_scaler",
          label: "RobustScaler (Outlier-Proof)",
          position: { x: 520, y: 160 },
          config: {},
          state: "idle",
        },
        "blk-split": {
          id: "blk-split",
          definitionId: "ml.train_test_split",
          label: "Stratified Split (80/20)",
          position: { x: 760, y: 160 },
          config: { test_size: 0.2, random_state: 42, target_column: "Class" },
          state: "idle",
        },
        "blk-rf": {
          id: "blk-rf",
          definitionId: "ml.random_forest_classifier",
          label: "Random Forest Classifier",
          position: { x: 1010, y: 100 },
          config: { n_estimators: 100, max_depth: 8, random_state: 42 },
          state: "idle",
        },
        "blk-pred": {
          id: "blk-pred",
          definitionId: "ml.predict",
          label: "Fraud Predictor",
          position: { x: 1260, y: 160 },
          config: {},
          state: "idle",
        },
        "blk-report": {
          id: "blk-report",
          definitionId: "eval.classification_report",
          label: "Classification Report",
          position: { x: 1510, y: 160 },
          config: {},
          state: "idle",
        },
      },
      connections: [
        { id: "c1", sourceBlockId: "blk-csv", sourcePortId: "dataset_out", targetBlockId: "blk-outlier", targetPortId: "dataset_in" },
        { id: "c2", sourceBlockId: "blk-outlier", sourcePortId: "dataset_out", targetBlockId: "blk-scale", targetPortId: "dataset_in" },
        { id: "c3", sourceBlockId: "blk-scale", sourcePortId: "dataset_out", targetBlockId: "blk-split", targetPortId: "dataset_in" },
        { id: "c4", sourceBlockId: "blk-split", sourcePortId: "train_data_out", targetBlockId: "blk-rf", targetPortId: "train_data_in" },
        { id: "c5", sourceBlockId: "blk-rf", sourcePortId: "model_out", targetBlockId: "blk-pred", targetPortId: "model_in" },
        { id: "c6", sourceBlockId: "blk-split", sourcePortId: "test_data_out", targetBlockId: "blk-pred", targetPortId: "test_data_in" },
        { id: "c7", sourceBlockId: "blk-pred", sourcePortId: "predictions_out", targetBlockId: "blk-report", targetPortId: "predictions_in" },
        { id: "c8", sourceBlockId: "blk-split", sourcePortId: "y_test_out", targetBlockId: "blk-report", targetPortId: "ground_truth_in" },
      ],
    },
  },
  {
    id: "template-kaggle-customer-segmentation",
    title: "Mall Customer Segmentation (K-Means & PCA)",
    category: "clustering",
    difficulty: "Beginner",
    description: "Unsupervised benchmark: loads customer demographics, standardizes continuous income & spending scores, decomposes variance into 2 principal components with PCA, partitions customers into 4 clusters with K-Means, and renders a 2D scatter visualizer.",
    tags: ["Customer Segmentation", "Clustering", "PCA", "K-Means", "Scatter Plot"],
    nodeCount: 5,
    edgeCount: 4,
    graph: {
      id: "wf-kaggle-segmentation",
      name: "Mall Customer Segmentation",
      version: "1.0.0",
      description: "Unsupervised customer clustering with PCA dimensionality reduction and K-Means",
      blocks: {
        "blk-csv": {
          id: "blk-csv",
          definitionId: "data.csv_loader",
          label: "Mall Customers Ingestion",
          position: { x: 50, y: 160 },
          config: { filePath: "data/mall_customers.csv" },
          state: "idle",
        },
        "blk-scale": {
          id: "blk-scale",
          definitionId: "prep.standard_scaler",
          label: "StandardScaler",
          position: { x: 300, y: 160 },
          config: { with_mean: true, with_std: true },
          state: "idle",
        },
        "blk-pca": {
          id: "blk-pca",
          definitionId: "prep.pca",
          label: "PCA (2 Components)",
          position: { x: 550, y: 160 },
          config: { n_components: 2 },
          state: "idle",
        },
        "blk-kmeans": {
          id: "blk-kmeans",
          definitionId: "ml.kmeans",
          label: "K-Means Clustering (k=4)",
          position: { x: 800, y: 100 },
          config: { n_clusters: 4, max_iter: 300, random_state: 42 },
          state: "idle",
        },
        "blk-scatter": {
          id: "blk-scatter",
          definitionId: "viz.scatter_plot",
          label: "Cluster Scatter Visualizer",
          position: { x: 800, y: 250 },
          config: { x_column: "pca_1", y_column: "pca_2" },
          state: "idle",
        },
      },
      connections: [
        { id: "c1", sourceBlockId: "blk-csv", sourcePortId: "dataset_out", targetBlockId: "blk-scale", targetPortId: "dataset_in" },
        { id: "c2", sourceBlockId: "blk-scale", sourcePortId: "dataset_out", targetBlockId: "blk-pca", targetPortId: "dataset_in" },
        { id: "c3", sourceBlockId: "blk-pca", sourcePortId: "dataset_out", targetBlockId: "blk-kmeans", targetPortId: "train_data_in" },
        { id: "c4", sourceBlockId: "blk-pca", sourcePortId: "dataset_out", targetBlockId: "blk-scatter", targetPortId: "dataset_in" },
      ],
    },
  },
];
