import { describe, it, expect } from "vitest";
import { PythonCodeGenerator } from "../code-generator.js";
import { createIrisWorkflowMock } from "@codebrix/shared";
import { getExecutionPlan } from "@codebrix/graph-engine";

describe("PythonCodeGenerator", () => {
  it("should compile the Iris workflow into a valid standalone Python script", () => {
    const workflow = createIrisWorkflowMock();
    const plan = getExecutionPlan(workflow);

    const generator = new PythonCodeGenerator();
    const result = generator.generate(workflow, plan);

    expect(result.workflowId).toBe(workflow.id);
    expect(result.executionOrder).toEqual(plan.executionOrder);
    expect(result.code).toBeTruthy();

    // 1. Script structure checks
    expect(result.code).toContain('"""\nAuto-generated by CodeBrix Python Code Generator');
    expect(result.code).toContain("import sys");
    expect(result.code).toContain("import json");
    expect(result.code).toContain("import pandas as pd");
    expect(result.code).toContain("from sklearn.ensemble import RandomForestClassifier");
    expect(result.code).toContain("from sklearn.metrics import accuracy_score");
    expect(result.code).toContain("from sklearn.metrics import confusion_matrix");
    expect(result.code).toContain("def iso_now() -> str:");
    expect(result.code).toContain("def emit_json(obj: dict):");
    expect(result.code).toContain("def main():");
    expect(result.code).toContain('if __name__ == "__main__":\n    main()');

    // 2. All 6 steps present in order
    plan.executionOrder.forEach((blockId, index) => {
      expect(result.code).toContain(`Step ${index + 1}:`);
      expect(result.code).toContain(`"payload": {"blockId": "${blockId}"}`);
    });

    // 3. Status and completion protocol checks
    expect(result.code).toContain('"event": "status"');
    expect(result.code).toContain('"payload": "running"');
    expect(result.code).toContain('"event": "done"');
    expect(result.code).toContain('"exitCode": 0');
    expect(result.code).toContain('"status": "success"');
    expect(result.code).toContain('"event": "error"');
  });

  it("should respect includeComments: false option", () => {
    const workflow = createIrisWorkflowMock();
    const plan = getExecutionPlan(workflow);

    const generator = new PythonCodeGenerator();
    const result = generator.generate(workflow, plan, { includeComments: false });

    expect(result.code).not.toContain("# Block:");
    expect(result.code).not.toContain("# Step 1:");
  });

  it("should respect includeProtocolHooks: false option", () => {
    const workflow = createIrisWorkflowMock();
    const plan = getExecutionPlan(workflow);

    const generator = new PythonCodeGenerator();
    const result = generator.generate(workflow, plan, { includeProtocolHooks: false });

    expect(result.code).not.toContain('"event": "block_start"');
    expect(result.code).not.toContain('"event": "block_done"');
  });
});
